id: 'skyvoid_worldgen_structures'
name: 'Sky Void with Structures'
author: 'BPR'
version: 1.0.8

require: 
  - src.plugins.worldgen.generate.base

data_pack:
  load: .
  
pipeline:
  - src.plugins.worldgen.get_empty_biomes.structures
